// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDussj7gF_kyi1h-L6TVjv14ZHUGJD5BvE',
    appId: '1:805620757740:web:7068b1f4f15ecb106de1c9',
    messagingSenderId: '805620757740',
    projectId: 'luminar-crm',
    authDomain: 'luminar-crm.firebaseapp.com',
    storageBucket: 'luminar-crm.firebasestorage.app',
    measurementId: 'G-FFBXSQ6PF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMavM4clvYxjA7bcOGVTpGA9MJp83FC6I',
    appId: '1:805620757740:android:2eeb60b287b857aa6de1c9',
    messagingSenderId: '805620757740',
    projectId: 'luminar-crm',
    storageBucket: 'luminar-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaaep9_pWzxvDY6h-QUoioYJCjx6ouT6I',
    appId: '1:805620757740:ios:b33f6418bc720c926de1c9',
    messagingSenderId: '805620757740',
    projectId: 'luminar-crm',
    storageBucket: 'luminar-crm.firebasestorage.app',
    iosBundleId: 'com.luminar.studentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaaep9_pWzxvDY6h-QUoioYJCjx6ouT6I',
    appId: '1:805620757740:ios:b33f6418bc720c926de1c9',
    messagingSenderId: '805620757740',
    projectId: 'luminar-crm',
    storageBucket: 'luminar-crm.firebasestorage.app',
    iosBundleId: 'com.luminar.studentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDussj7gF_kyi1h-L6TVjv14ZHUGJD5BvE',
    appId: '1:805620757740:web:7068b1f4f15ecb106de1c9',
    messagingSenderId: '805620757740',
    projectId: 'luminar-crm',
    authDomain: 'luminar-crm.firebaseapp.com',
    storageBucket: 'luminar-crm.firebasestorage.app',
    measurementId: 'G-FFBXSQ6PF4',
  );
}
